// examples/react/src/demos/calendar/Default.tsx
import { DoranDate, faIR, type Locale } from '@doranjs/core';
import { DoranCalendar } from '@doranjs/react';
import { useState } from 'react';

// The default calendar: dropdown month/year header, Saturday-first weeks, RTL.
export default function Default({ locale = faIR }: { locale?: Locale }) {
  const [value, setValue] = useState(DoranDate.now());
  return (
    <>
      <DoranCalendar value={value} onChange={setValue} locale={locale} />
      <p className="result">{value.withLocale(locale).format('dddd D MMMM YYYY')}</p>
    </>
  );
}

// examples/svelte/src/demos/calendar/Default.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranCalendar } from '@doranjs/svelte';

  // The default calendar: dropdown month/year header, Saturday-first weeks, RTL.
  // bind:value carries a DoranDate.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = DoranDate.now();
</script>

<DoranCalendar bind:value locale={lang} />
{#if value}<p class="result">{value.withLocale(lang).format('dddd D MMMM YYYY')}</p>{/if}
