// examples/react/src/demos/calendar/Holidays.tsx
import { DoranDate, faIR, type Locale } from '@doranjs/core';
import { getHolidaysOn } from '@doranjs/holidays';
import { DoranCalendar } from '@doranjs/react';
import { useCallback, useState } from 'react';

// `isHoliday` marks days with a dot and the holiday color. Here it's wired to
// the official-holiday data from @doranjs/holidays.
export default function Holidays({ locale = faIR }: { locale?: Locale }) {
  const [value, setValue] = useState(DoranDate.now());
  const isHoliday = useCallback((day: DoranDate) => getHolidaysOn(day).some((h) => h.official), []);
  return <DoranCalendar value={value} onChange={setValue} isHoliday={isHoliday} locale={locale} />;
}

// examples/svelte/src/demos/calendar/Holidays.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranCalendar } from '@doranjs/svelte';

  // show-holidays marks official-holiday days with a dot and the holiday color,
  // wired to the built-in @doranjs/holidays data (no per-day callback needed).
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = DoranDate.now();
</script>

<DoranCalendar bind:value locale={lang} show-holidays />
