// examples/angular/src/demos/calendar/separate-header.component.ts
import { Component, input } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { DoranDate } from '@doranjs/core';
import { DoranCalendar } from '@doranjs/angular';

// headerMode="separate" renders native month and year <select>s instead of the
// in-place dropdown panels.
@Component({
  selector: 'demo-cal-separate-header',
  standalone: true,
  imports: [ReactiveFormsModule, DoranCalendar],
  template: `<dr-calendar [formControl]="value" [locale]="lang()" headerMode="separate" />`,
})
export class CalSeparateHeader {
  readonly lang = input<'fa' | 'en'>('fa');
  readonly value = new FormControl<DoranDate | null>(DoranDate.now());
}

// examples/svelte/src/demos/calendar/SeparateHeader.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranCalendar } from '@doranjs/svelte';

  // header-mode="separate" renders native month and year <select>s instead of the
  // in-place dropdown panels.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = DoranDate.now();
</script>

<DoranCalendar bind:value locale={lang} header-mode="separate" />
