// examples/react/src/demos/calendar/SeparateHeader.tsx
import { DoranDate, faIR, type Locale } from '@doranjs/core';
import { DoranCalendar } from '@doranjs/react';
import { useState } from 'react';

// `headerMode="separate"` renders native month and year <select>s instead of
// the in-place dropdown panels.
export default function SeparateHeader({ locale = faIR }: { locale?: Locale }) {
  const [value, setValue] = useState(DoranDate.now());
  return <DoranCalendar value={value} onChange={setValue} headerMode="separate" locale={locale} />;
}

// examples/svelte/src/demos/calendar/SeparateHeader.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranCalendar } from '@doranjs/svelte';

  // header-mode="separate" renders native month and year <select>s instead of the
  // in-place dropdown panels.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = DoranDate.now();
</script>

<DoranCalendar bind:value locale={lang} header-mode="separate" />
