// examples/angular/src/demos/calendar/weekends.component.ts
import { Component, input } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { DoranDate } from '@doranjs/core';
import { DoranCalendar } from '@doranjs/angular';

// weekends overrides which weekday indices are styled as weekend (0 = Saturday).
// The default is [6] (Friday); here we mark both Thursday and Friday.
@Component({
  selector: 'demo-cal-weekends',
  standalone: true,
  imports: [ReactiveFormsModule, DoranCalendar],
  template: `<dr-calendar [formControl]="value" [locale]="lang()" [weekends]="[5, 6]" />`,
})
export class CalWeekends {
  readonly lang = input<'fa' | 'en'>('fa');
  readonly value = new FormControl<DoranDate | null>(DoranDate.now());
}

// examples/svelte/src/demos/calendar/Weekends.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranCalendar } from '@doranjs/svelte';

  // weekends overrides which weekday indices are styled as weekend (0 = Saturday).
  // The default is [6] (Friday); here we mark both Thursday and Friday.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = DoranDate.now();
</script>

<DoranCalendar bind:value locale={lang} weekends="5,6" />
