// examples/svelte/src/demos/calendar/Default.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranCalendar } from '@doranjs/svelte';

  // The default calendar: dropdown month/year header, Saturday-first weeks, RTL.
  // bind:value carries a DoranDate.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = DoranDate.now();
</script>

<DoranCalendar bind:value locale={lang} />
{#if value}<p class="result">{value.withLocale(lang).format('dddd D MMMM YYYY')}</p>{/if}

// examples/vue/src/demos/calendar/Default.vue
<script setup lang="ts">
import { DoranDate } from '@doranjs/core';
import { DoranCalendar } from '@doranjs/vue';
import { shallowRef } from 'vue';

// The default calendar: dropdown month/year header, Saturday-first weeks, RTL.
// v-model carries a DoranDate; shallowRef keeps it un-proxied.
const { lang = 'fa' } = defineProps<{ lang?: 'fa' | 'en' }>();
const value = shallowRef<DoranDate | null>(DoranDate.now());
</script>

<template>
  <DoranCalendar v-model="value" :locale="lang" />
  <p v-if="value" class="result">{{ value.withLocale(lang).format('dddd D MMMM YYYY') }}</p>
</template>
