// examples/svelte/src/demos/calendar/LocaleDemo.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranCalendar } from '@doranjs/svelte';

  // The locale attribute switches the calendar's language. locale="en" renders
  // English month/weekday names, Latin digits, and localized footer actions.
  let value: DoranDate | null = DoranDate.now();
</script>

<DoranCalendar bind:value locale="en" />
{#if value}<p class="result">{value.withLocale('en').format('dddd D MMMM YYYY')}</p>{/if}

// examples/vue/src/demos/calendar/LocaleDemo.vue
<script setup lang="ts">
import { DoranDate } from '@doranjs/core';
import { DoranCalendar } from '@doranjs/vue';
import { shallowRef } from 'vue';

// The locale attribute switches the calendar's language. locale="en" renders
// English month/weekday names, Latin digits, and localized footer actions.
const value = shallowRef<DoranDate | null>(DoranDate.now());
</script>

<template>
  <DoranCalendar v-model="value" locale="en" />
  <p v-if="value" class="result">{{ value.withLocale('en').format('dddd D MMMM YYYY') }}</p>
</template>
