// examples/svelte/src/demos/calendar/SeparateHeader.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranCalendar } from '@doranjs/svelte';

  // header-mode="separate" renders native month and year <select>s instead of the
  // in-place dropdown panels.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = DoranDate.now();
</script>

<DoranCalendar bind:value locale={lang} header-mode="separate" />

// examples/vue/src/demos/calendar/SeparateHeader.vue
<script setup lang="ts">
import { DoranDate } from '@doranjs/core';
import { DoranCalendar } from '@doranjs/vue';
import { shallowRef } from 'vue';

// header-mode="separate" renders native month and year <select>s instead of the
// in-place dropdown panels.
const { lang = 'fa' } = defineProps<{ lang?: 'fa' | 'en' }>();
const value = shallowRef<DoranDate | null>(DoranDate.now());
</script>

<template>
  <DoranCalendar v-model="value" :locale="lang" header-mode="separate" />
</template>
