// examples/angular/src/demos/datepicker/pick-only.component.ts
import { Component, input } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { type DoranDate } from '@doranjs/core';
import { DoranDatePicker } from '@doranjs/angular';

@Component({
  selector: 'demo-dp-pick-only',
  standalone: true,
  imports: [ReactiveFormsModule, DoranDatePicker],
  template: `
    <!-- The trigger becomes a button: the whole field opens the calendar and no
         on-screen keyboard ever appears over it. -->
    <dr-date-picker
      [formControl]="value"
      [locale]="lang()"
      [editable]="false"
      mode="auto"
      inputWidth="14rem"
    />
  `,
})
export class DpPickOnly {
  readonly lang = input<'fa' | 'en'>('fa');
  readonly value = new FormControl<DoranDate | null>(null);
}

// examples/svelte/src/demos/datepicker/PickOnly.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranDatePicker } from '@doranjs/svelte';

  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = null;
</script>

<!-- The trigger becomes a button: the whole field opens the calendar and no
     on-screen keyboard ever appears over it. -->
<DoranDatePicker bind:value locale={lang} editable="false" mode="auto" input-width="14rem" />
