// examples/svelte/src/demo/CodePanel.svelte
<script lang="ts">
  import { mode, t } from '../i18n/store';
  import { CODE_THEMES, getHighlighter } from './highlighter';

  export let code: string;
  export let lang = 'svelte';

  let html = '';
  let copied = false;

  // Re-highlight whenever the code or the light/dark mode changes. The code is
  // always LTR regardless of page direction.
  $: void highlight(code, lang, $mode);
  async function highlight(src: string, grammar: string, m: 'light' | 'dark') {
    try {
      const hl = await getHighlighter();
      html = hl.codeToHtml(src.trimEnd(), {
        lang: grammar,
        theme: m === 'dark' ? CODE_THEMES.dark : CODE_THEMES.light,
      });
    } catch {
      html = '';
    }
  }

  async function copy() {
    await navigator.clipboard.writeText(code);
    copied = true;
    setTimeout(() => (copied = false), 1500);
  }
</script>

<div class="code-panel" dir="ltr">
  <div class="code-panel__bar">
    <span class="code-panel__lang">{lang}</span>
    <button type="button" class="code-panel__copy" on:click={copy}>
      {copied ? $t('copied') : $t('copy')}
    </button>
  </div>
  {#if html}
    <!-- Shiki output is generated from our own trusted source strings. -->
    <div class="code-panel__shiki">{@html html}</div>
  {:else}
    <pre class="code-panel__pre"><code>{code.trimEnd()}</code></pre>
  {/if}
</div>

// examples/react/src/demo/CodePanel.tsx
import { useEffect, useState } from 'react';
import { useTheme } from '@doranjs/ui';
import { useLang } from '../i18n/LangProvider';
import { CODE_THEMES, getHighlighter } from './highlighter';

export interface CodePanelProps {
  /** Raw source text of the demo, imported via `?raw`. */
  code: string;
  /** Language grammar to highlight with. Defaults to `tsx`. */
  lang?: string;
}

/**
 * Renders a demo's source with Shiki syntax highlighting and a copy button. The
 * highlight theme follows the app's light/dark mode, and the code is always LTR
 * regardless of page direction. Pass the result of a `?raw` import so what's
 * shown is exactly what runs.
 */
export function CodePanel({ code, lang = 'tsx' }: CodePanelProps) {
  const { mode } = useTheme();
  const { t } = useLang();
  const [copied, setCopied] = useState(false);
  const [html, setHtml] = useState('');

  useEffect(() => {
    let cancelled = false;
    getHighlighter()
      .then((hl) => {
        const out = hl.codeToHtml(code.trimEnd(), {
          lang,
          theme: mode === 'dark' ? CODE_THEMES.dark : CODE_THEMES.light,
        });
        if (!cancelled) setHtml(out);
      })
      .catch(() => {
        if (!cancelled) setHtml('');
      });
    return () => {
      cancelled = true;
    };
  }, [code, lang, mode]);

  async function copy() {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="code-panel" dir="ltr">
      <div className="code-panel__bar">
        <span className="code-panel__lang">{lang}</span>
        <button type="button" className="code-panel__copy" onClick={copy}>
          {copied ? t('copied') : t('copy')}
        </button>
      </div>
      {html ? (
        <div className="code-panel__shiki" dangerouslySetInnerHTML={{ __html: html }} />
      ) : (
        // Before Shiki resolves, show the raw source so nothing flashes empty.
        <pre className="code-panel__pre">
          <code>{code.trimEnd()}</code>
        </pre>
      )}
    </div>
  );
}
