// examples/angular/src/demo/code-panel.component.ts
import { Component, effect, inject, input, signal } from '@angular/core';
import { DomSanitizer, type SafeHtml } from '@angular/platform-browser';
import { AppState } from '../i18n/app.service';
import { CODE_THEMES, getHighlighter } from './highlighter';

// Renders a demo's source with Shiki highlighting and a copy button. The theme
// follows the app's light/dark mode; the code is always LTR.
@Component({
  selector: 'demo-code-panel',
  standalone: true,
  template: `
    <div class="code-panel" dir="ltr">
      <div class="code-panel__bar">
        <span class="code-panel__lang">{{ lang() }}</span>
        <button type="button" class="code-panel__copy" (click)="copy()">
          {{ copied() ? app.t('copied') : app.t('copy') }}
        </button>
      </div>
      @if (html()) {
        <div class="code-panel__shiki" [innerHTML]="html()"></div>
      } @else {
        <pre class="code-panel__pre"><code>{{ code().trimEnd() }}</code></pre>
      }
    </div>
  `,
})
export class CodePanel {
  readonly code = input.required<string>();
  readonly lang = input('angular-ts');
  readonly app = inject(AppState);
  private sanitizer = inject(DomSanitizer);
  readonly copied = signal(false);
  readonly html = signal<SafeHtml | ''>('');

  constructor() {
    effect(() => {
      const mode = this.app.mode();
      const code = this.code();
      const lang = this.lang();
      getHighlighter()
        .then((hl) => {
          const out = hl.codeToHtml(code.trimEnd(), {
            lang,
            theme: mode === 'dark' ? CODE_THEMES.dark : CODE_THEMES.light,
          });
          this.html.set(this.sanitizer.bypassSecurityTrustHtml(out));
        })
        .catch(() => this.html.set(''));
    });
  }

  async copy(): Promise<void> {
    await navigator.clipboard.writeText(this.code());
    this.copied.set(true);
    setTimeout(() => this.copied.set(false), 1500);
  }
}

// examples/react/src/demo/CodePanel.tsx
import { useEffect, useState } from 'react';
import { useTheme } from '@doranjs/ui';
import { useLang } from '../i18n/LangProvider';
import { CODE_THEMES, getHighlighter } from './highlighter';

export interface CodePanelProps {
  /** Raw source text of the demo, imported via `?raw`. */
  code: string;
  /** Language grammar to highlight with. Defaults to `tsx`. */
  lang?: string;
}

/**
 * Renders a demo's source with Shiki syntax highlighting and a copy button. The
 * highlight theme follows the app's light/dark mode, and the code is always LTR
 * regardless of page direction. Pass the result of a `?raw` import so what's
 * shown is exactly what runs.
 */
export function CodePanel({ code, lang = 'tsx' }: CodePanelProps) {
  const { mode } = useTheme();
  const { t } = useLang();
  const [copied, setCopied] = useState(false);
  const [html, setHtml] = useState('');

  useEffect(() => {
    let cancelled = false;
    getHighlighter()
      .then((hl) => {
        const out = hl.codeToHtml(code.trimEnd(), {
          lang,
          theme: mode === 'dark' ? CODE_THEMES.dark : CODE_THEMES.light,
        });
        if (!cancelled) setHtml(out);
      })
      .catch(() => {
        if (!cancelled) setHtml('');
      });
    return () => {
      cancelled = true;
    };
  }, [code, lang, mode]);

  async function copy() {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="code-panel" dir="ltr">
      <div className="code-panel__bar">
        <span className="code-panel__lang">{lang}</span>
        <button type="button" className="code-panel__copy" onClick={copy}>
          {copied ? t('copied') : t('copy')}
        </button>
      </div>
      {html ? (
        <div className="code-panel__shiki" dangerouslySetInnerHTML={{ __html: html }} />
      ) : (
        // Before Shiki resolves, show the raw source so nothing flashes empty.
        <pre className="code-panel__pre">
          <code>{code.trimEnd()}</code>
        </pre>
      )}
    </div>
  );
}
