// examples/svelte/src/demos/nlpinput/Default.svelte
<script lang="ts">
  import { DoranNlpInput } from '@doranjs/svelte';

  // Type natural Persian like «پنجشنبهٔ بعد ساعت ۵»; a live preview of the parsed
  // date appears beneath the input. bind:value is the text string.
  export let lang: 'fa' | 'en' = 'fa';
  let value = 'پنجشنبهٔ بعد ساعت ۵';
</script>

<DoranNlpInput bind:value locale={lang} placeholder="مثلاً: فردا ساعت ۹ صبح" />

// examples/vue/src/demos/nlpinput/Default.vue
<script setup lang="ts">
import { DoranNlpInput } from '@doranjs/vue';
import { ref } from 'vue';

// Type natural Persian like «پنجشنبهٔ بعد ساعت ۵»; a live preview of the parsed
// date appears beneath the input. v-model is the text string.
const { lang = 'fa' } = defineProps<{ lang?: 'fa' | 'en' }>();
const text = ref('پنجشنبهٔ بعد ساعت ۵');
</script>

<template>
  <DoranNlpInput v-model="text" :locale="lang" placeholder="مثلاً: فردا ساعت ۹ صبح" />
</template>
