// examples/svelte/src/demos/datepicker/Default.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranDatePicker } from '@doranjs/svelte';

  // A date input that opens a calendar popover on click. bind:value is a DoranDate.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = DoranDate.now();
</script>

<DoranDatePicker bind:value locale={lang} />

// examples/react/src/demos/datepicker/Default.tsx
import { DoranDate, faIR, type Locale } from '@doranjs/core';
import { DoranDatePicker } from '@doranjs/react';
import { useState } from 'react';

// A date input that opens a calendar popover on click.
export default function Default({ locale = faIR }: { locale?: Locale }) {
  const [value, setValue] = useState<DoranDate | null>(DoranDate.now());
  return <DoranDatePicker value={value} onChange={setValue} locale={locale} />;
}
