// examples/svelte/src/demos/datepicker/PickOnly.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranDatePicker } from '@doranjs/svelte';

  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = null;
</script>

<!-- The trigger becomes a button: the whole field opens the calendar and no
     on-screen keyboard ever appears over it. -->
<DoranDatePicker bind:value locale={lang} editable="false" mode="auto" input-width="14rem" />

// examples/react/src/demos/datepicker/PickOnly.tsx
import { type DoranDate } from '@doranjs/core';
import { DoranDatePicker } from '@doranjs/react';
import { useState } from 'react';
import type { Locale } from '@doranjs/core';

export default function PickOnly({ locale }: { locale: Locale }) {
  const [value, setValue] = useState<DoranDate | null>(null);

  return (
    <DoranDatePicker
      value={value}
      onChange={setValue}
      locale={locale}
      // The trigger becomes a button: the whole field opens the calendar and
      // no on-screen keyboard ever appears over it.
      editable={false}
      mode="auto"
      inputWidth="14rem"
    />
  );
}
