// examples/svelte/src/demos/datepicker/WithTime.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranDatePicker } from '@doranjs/svelte';

  // with-time adds a time picker to the popover; a custom display format shows the
  // time alongside the date.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = DoranDate.now();
</script>

<DoranDatePicker bind:value locale={lang} with-time format="dddd D MMMM YYYY — HH:mm" />

// examples/react/src/demos/datepicker/WithTime.tsx
import { DoranDate, faIR, type Locale } from '@doranjs/core';
import { DoranDatePicker } from '@doranjs/react';
import { useState } from 'react';

// `withTime` adds a time picker to the popover and a custom display `format`
// shows the time alongside the date.
export default function WithTime({ locale = faIR }: { locale?: Locale }) {
  const [value, setValue] = useState<DoranDate | null>(DoranDate.now());
  return (
    <DoranDatePicker
      value={value}
      onChange={setValue}
      withTime
      format="dddd D MMMM YYYY — HH:mm"
      locale={locale}
    />
  );
}
