// examples/svelte/src/demos/nlpinput/Default.svelte
<script lang="ts">
  import { DoranNlpInput } from '@doranjs/svelte';

  // Type natural Persian like «پنجشنبهٔ بعد ساعت ۵»; a live preview of the parsed
  // date appears beneath the input. bind:value is the text string.
  export let lang: 'fa' | 'en' = 'fa';
  let value = 'پنجشنبهٔ بعد ساعت ۵';
</script>

<DoranNlpInput bind:value locale={lang} placeholder="مثلاً: فردا ساعت ۹ صبح" />

// examples/react/src/demos/nlpinput/Default.tsx
import { faIR, type Locale } from '@doranjs/core';
import { DoranNlpInput } from '@doranjs/react';

// Type natural Persian like «پنجشنبهٔ بعد ساعت ۵»; a live preview of the parsed
// date appears beneath the input (`showHint`, on by default).
export default function Default({ locale = faIR }: { locale?: Locale }) {
  return (
    <DoranNlpInput
      defaultValue="پنجشنبهٔ بعد ساعت ۵"
      placeholder="مثلاً: فردا ساعت ۹ صبح"
      locale={locale}
    />
  );
}
