// examples/svelte/src/demos/nlpinput/Default.svelte
<script lang="ts">
  import { DoranNlpInput } from '@doranjs/svelte';

  // Type natural Persian like «پنجشنبهٔ بعد ساعت ۵»; a live preview of the parsed
  // date appears beneath the input. bind:value is the text string.
  export let lang: 'fa' | 'en' = 'fa';
  let value = 'پنجشنبهٔ بعد ساعت ۵';
</script>

<DoranNlpInput bind:value locale={lang} placeholder="مثلاً: فردا ساعت ۹ صبح" />

// examples/angular/src/demos/nlpinput/default.component.ts
import { Component, input } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { DoranNlpInput } from '@doranjs/angular';

// Type natural Persian like «پنجشنبهٔ بعد ساعت ۵»; a live preview of the parsed
// date appears beneath the input. The form value is the text string.
@Component({
  selector: 'demo-nlp-default',
  standalone: true,
  imports: [ReactiveFormsModule, DoranNlpInput],
  template: `<dr-nlp-input
    [formControl]="value"
    [locale]="lang()"
    placeholder="مثلاً: فردا ساعت ۹ صبح"
  />`,
})
export class NlpDefault {
  readonly lang = input<'fa' | 'en'>('fa');
  readonly value = new FormControl('پنجشنبهٔ بعد ساعت ۵');
}
