// examples/svelte/src/demos/calendar/WithTime.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranCalendar } from '@doranjs/svelte';

  // with-time adds a time picker and carries the time-of-day on the selected value.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDate | null = DoranDate.now();
</script>

<DoranCalendar bind:value locale={lang} with-time />
{#if value}<p class="result">{value.withLocale(lang).format('dddd D MMMM YYYY — HH:mm')}</p>{/if}

// examples/react/src/demos/calendar/WithTime.tsx
import { DoranDate, faIR, type Locale } from '@doranjs/core';
import { DoranCalendar } from '@doranjs/react';
import { useState } from 'react';

// `withTime` adds a time picker and carries the time-of-day on the selected
// value. `minuteStep` controls the minute increment.
export default function WithTime({ locale = faIR }: { locale?: Locale }) {
  const [value, setValue] = useState(DoranDate.now());
  return (
    <>
      <DoranCalendar
        value={value}
        onChange={setValue}
        withTime
        defaultTime={{ hour: 9, minute: 0 }}
        locale={locale}
      />
      <p className="result">{value.withLocale(locale).format('dddd D MMMM YYYY — HH:mm')}</p>
    </>
  );
}
