// examples/svelte/src/demos/rangepicker/Holidays.svelte
<script lang="ts">
  import { DoranRangePicker, type DoranDateRange } from '@doranjs/svelte';

  // The same holiday/weekend marking as the calendar — show-holidays and weekends
  // carry straight over to the range picker.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDateRange = { start: null, end: null };
</script>

<DoranRangePicker bind:value locale={lang} show-holidays weekends="5,6" />

// examples/vue/src/demos/rangepicker/Holidays.vue
<script setup lang="ts">
import { DoranRangePicker, type DoranDateRange } from '@doranjs/vue';
import { shallowRef } from 'vue';

// The same holiday/weekend marking as the calendar — show-holidays and weekends
// carry straight over to the range picker.
const { lang = 'fa' } = defineProps<{ lang?: 'fa' | 'en' }>();
const range = shallowRef<DoranDateRange>({ start: null, end: null });
</script>

<template>
  <DoranRangePicker v-model="range" :locale="lang" show-holidays weekends="5,6" />
</template>
