// examples/react/src/demos/nlpinput/Resolve.tsx
import { faIR, type Locale } from '@doranjs/core';
import { DoranNlpInput } from '@doranjs/react';
import { type ParseResult } from '@doranjs/nlp';
import { useState } from 'react';

// `onResolve` hands you the parsed result (a DoranDate plus confidence) so you
// can use it in your app.
export default function Resolve({ locale = faIR }: { locale?: Locale }) {
  const [result, setResult] = useState<ParseResult | null>(null);
  return (
    <>
      <DoranNlpInput defaultValue="فردا ساعت ۱۰" onResolve={setResult} locale={locale} />
      <p className="result">
        {result ? result.date.withLocale(locale).format('dddd D MMMM YYYY — HH:mm') : '—'}
      </p>
    </>
  );
}

// examples/svelte/src/demos/nlpinput/Resolve.svelte
<script lang="ts">
  import { type ParseResult } from '@doranjs/nlp';
  import { DoranNlpInput } from '@doranjs/svelte';

  // The `resolve` event hands you the parsed result (a DoranDate plus confidence)
  // so you can use it in your app.
  export let lang: 'fa' | 'en' = 'fa';
  let value = 'فردا ساعت ۱۰';
  let result: ParseResult | null = null;
</script>

<DoranNlpInput
  bind:value
  locale={lang}
  on:resolve={(e) => (result = e.detail as ParseResult | null)}
/>
<p class="result">
  {result ? result.date.withLocale(lang).format('dddd D MMMM YYYY — HH:mm') : '—'}
</p>
