// examples/svelte/src/demos/rangepicker/Default.svelte
<script lang="ts">
  import { DoranRangePicker, type DoranDateRange } from '@doranjs/svelte';

  // Click a start day, then an end day. bind:value is a { start, end } of DoranDate.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDateRange = { start: null, end: null };
</script>

<DoranRangePicker bind:value locale={lang} />

// examples/react/src/demos/rangepicker/Default.tsx
import { faIR, type Locale } from '@doranjs/core';
import { DoranRangePicker, type DateRange } from '@doranjs/react';
import { useState } from 'react';

// Click a start day, then an end day. The hook manages the start/end handshake.
export default function Default({ locale = faIR }: { locale?: Locale }) {
  const [range, setRange] = useState<DateRange>({ start: null, end: null });
  return <DoranRangePicker value={range} onChange={setRange} locale={locale} />;
}
