// examples/svelte/src/sections/NlpInputSection.svelte
<script lang="ts">
  import { lang, t } from '../i18n/store';
  import DemoCard from '../demo/DemoCard.svelte';
  import Section from '../demo/Section.svelte';
  import Default from '../demos/nlpinput/Default.svelte';
  import DefaultSrc from '../demos/nlpinput/Default.svelte?raw';
  import Resolve from '../demos/nlpinput/Resolve.svelte';
  import ResolveSrc from '../demos/nlpinput/Resolve.svelte?raw';
</script>

<Section id="nlp-input" title="<DoranNlpInput>" intro={$t('nlpIntro')}>
  <DemoCard title={$t('nlpDefaultTitle')} description={$t('nlpDefaultDesc')} code={DefaultSrc}>
    <Default lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('nlpResolveTitle')} description={$t('nlpResolveDesc')} code={ResolveSrc}>
    <Resolve lang={$lang} />
  </DemoCard>
</Section>

// examples/react/src/sections/NlpInputSection.tsx
import { useLang } from '../i18n/LangProvider';
import { DemoCard } from '../demo/DemoCard';
import { Section } from '../demo/Section';

import Default from '../demos/nlpinput/Default';
import DefaultSrc from '../demos/nlpinput/Default?raw';
import Suggestions from '../demos/nlpinput/Suggestions';
import SuggestionsSrc from '../demos/nlpinput/Suggestions?raw';
import Resolve from '../demos/nlpinput/Resolve';
import ResolveSrc from '../demos/nlpinput/Resolve?raw';

export function NlpInputSection() {
  const { t, locale } = useLang();
  return (
    <Section id="nlp-input" title="<DoranNlpInput>" intro={t('nlpIntro')}>
      <DemoCard title={t('nlpDefaultTitle')} description={t('nlpDefaultDesc')} code={DefaultSrc}>
        <Default locale={locale} />
      </DemoCard>
      <DemoCard
        title={t('nlpSuggestTitle')}
        description={t('nlpSuggestDesc')}
        code={SuggestionsSrc}
      >
        <Suggestions locale={locale} />
      </DemoCard>
      <DemoCard title={t('nlpResolveTitle')} description={t('nlpResolveDesc')} code={ResolveSrc}>
        <Resolve locale={locale} />
      </DemoCard>
    </Section>
  );
}
