// examples/svelte/src/sections/CalendarSection.svelte
<script lang="ts">
  import { lang, t } from '../i18n/store';
  import DemoCard from '../demo/DemoCard.svelte';
  import Section from '../demo/Section.svelte';
  import Default from '../demos/calendar/Default.svelte';
  import DefaultSrc from '../demos/calendar/Default.svelte?raw';
  import SeparateHeader from '../demos/calendar/SeparateHeader.svelte';
  import SeparateHeaderSrc from '../demos/calendar/SeparateHeader.svelte?raw';
  import WithTime from '../demos/calendar/WithTime.svelte';
  import WithTimeSrc from '../demos/calendar/WithTime.svelte?raw';
  import Holidays from '../demos/calendar/Holidays.svelte';
  import HolidaysSrc from '../demos/calendar/Holidays.svelte?raw';
  import Weekends from '../demos/calendar/Weekends.svelte';
  import WeekendsSrc from '../demos/calendar/Weekends.svelte?raw';
  import LocaleDemo from '../demos/calendar/LocaleDemo.svelte';
  import LocaleDemoSrc from '../demos/calendar/LocaleDemo.svelte?raw';
  import Headless from '../demos/calendar/Headless.svelte';
  import HeadlessSrc from '../demos/calendar/Headless.svelte?raw';
</script>

<Section id="calendar" title="<DoranCalendar>" intro={$t('calIntro')}>
  <DemoCard title={$t('wgEventsTitle')} description={$t('wgEventsDesc')} code={WidgetsSrc}>
    <Widgets lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('calDefaultTitle')} description={$t('calDefaultDesc')} code={DefaultSrc}>
    <Default lang={$lang} />
  </DemoCard>
  <DemoCard
    title={$t('calSeparateTitle')}
    description={$t('calSeparateDesc')}
    code={SeparateHeaderSrc}
  >
    <SeparateHeader lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('calTimeTitle')} description={$t('calTimeDesc')} code={WithTimeSrc}>
    <WithTime lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('calHolidaysTitle')} description={$t('calHolidaysDesc')} code={HolidaysSrc}>
    <Holidays lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('calWeekendsTitle')} description={$t('calWeekendsDesc')} code={WeekendsSrc}>
    <Weekends lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('calLocaleTitle')} description={$t('calLocaleDesc')} code={LocaleDemoSrc}>
    <LocaleDemo />
  </DemoCard>
  <DemoCard title={$t('calHeadlessTitle')} description={$t('calHeadlessDesc')} code={HeadlessSrc}>
    <Headless lang={$lang} />
  </DemoCard>
</Section>

// examples/vue/src/sections/CalendarSection.vue
<script setup lang="ts">
import { useApp } from '../i18n/context';
import DemoCard from '../demo/DemoCard.vue';
import Section from '../demo/Section.vue';
import Default from '../demos/calendar/Default.vue';
import DefaultSrc from '../demos/calendar/Default.vue?raw';
import SeparateHeader from '../demos/calendar/SeparateHeader.vue';
import SeparateHeaderSrc from '../demos/calendar/SeparateHeader.vue?raw';
import WithTime from '../demos/calendar/WithTime.vue';
import WithTimeSrc from '../demos/calendar/WithTime.vue?raw';
import Holidays from '../demos/calendar/Holidays.vue';
import HolidaysSrc from '../demos/calendar/Holidays.vue?raw';
import Weekends from '../demos/calendar/Weekends.vue';
import WeekendsSrc from '../demos/calendar/Weekends.vue?raw';
import LocaleDemo from '../demos/calendar/LocaleDemo.vue';
import LocaleDemoSrc from '../demos/calendar/LocaleDemo.vue?raw';
import Widgets from '../demos/calendar/Widgets.vue';
import WidgetsSrc from '../demos/calendar/Widgets.vue?raw';
import Headless from '../demos/calendar/Headless.vue';
import HeadlessSrc from '../demos/calendar/Headless.vue?raw';

const app = useApp();
</script>

<template>
  <Section id="calendar" title="<DoranCalendar>" :intro="app.t('calIntro')">
    <DemoCard
      :title="app.t('calDefaultTitle')"
      :description="app.t('calDefaultDesc')"
      :code="DefaultSrc"
    >
      <Default :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('wgEventsTitle')"
      :description="app.t('wgEventsDesc')"
      :code="WidgetsSrc"
    >
      <Widgets :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('calSeparateTitle')"
      :description="app.t('calSeparateDesc')"
      :code="SeparateHeaderSrc"
    >
      <SeparateHeader :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('calTimeTitle')"
      :description="app.t('calTimeDesc')"
      :code="WithTimeSrc"
    >
      <WithTime :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('calHolidaysTitle')"
      :description="app.t('calHolidaysDesc')"
      :code="HolidaysSrc"
    >
      <Holidays :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('calWeekendsTitle')"
      :description="app.t('calWeekendsDesc')"
      :code="WeekendsSrc"
    >
      <Weekends :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('calLocaleTitle')"
      :description="app.t('calLocaleDesc')"
      :code="LocaleDemoSrc"
    >
      <LocaleDemo />
    </DemoCard>
    <DemoCard
      :title="app.t('calHeadlessTitle')"
      :description="app.t('calHeadlessDesc')"
      :code="HeadlessSrc"
    >
      <Headless :lang="app.lang()" />
    </DemoCard>
  </Section>
</template>
