// examples/svelte/src/sections/NlpInputSection.svelte
<script lang="ts">
  import { lang, t } from '../i18n/store';
  import DemoCard from '../demo/DemoCard.svelte';
  import Section from '../demo/Section.svelte';
  import Default from '../demos/nlpinput/Default.svelte';
  import DefaultSrc from '../demos/nlpinput/Default.svelte?raw';
  import Resolve from '../demos/nlpinput/Resolve.svelte';
  import ResolveSrc from '../demos/nlpinput/Resolve.svelte?raw';
</script>

<Section id="nlp-input" title="<DoranNlpInput>" intro={$t('nlpIntro')}>
  <DemoCard title={$t('nlpDefaultTitle')} description={$t('nlpDefaultDesc')} code={DefaultSrc}>
    <Default lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('nlpResolveTitle')} description={$t('nlpResolveDesc')} code={ResolveSrc}>
    <Resolve lang={$lang} />
  </DemoCard>
</Section>

// examples/vue/src/sections/NlpInputSection.vue
<script setup lang="ts">
import { useApp } from '../i18n/context';
import DemoCard from '../demo/DemoCard.vue';
import Section from '../demo/Section.vue';
import Default from '../demos/nlpinput/Default.vue';
import DefaultSrc from '../demos/nlpinput/Default.vue?raw';
import Resolve from '../demos/nlpinput/Resolve.vue';
import ResolveSrc from '../demos/nlpinput/Resolve.vue?raw';

const app = useApp();
</script>

<template>
  <Section id="nlp-input" title="<DoranNlpInput>" :intro="app.t('nlpIntro')">
    <DemoCard
      :title="app.t('nlpDefaultTitle')"
      :description="app.t('nlpDefaultDesc')"
      :code="DefaultSrc"
    >
      <Default :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('nlpResolveTitle')"
      :description="app.t('nlpResolveDesc')"
      :code="ResolveSrc"
    >
      <Resolve :lang="app.lang()" />
    </DemoCard>
  </Section>
</template>
