// packages/angular/src/provider.ts
import { Component, forwardRef, InjectionToken, Input } from '@angular/core';

/** Subtree defaults supplied by {@link DoranProvider}. */
export interface DoranDefaults {
  /** Locale attribute for the underlying elements (`'fa'` | `'en'`). */
  locale?: string;
  /** IANA time zone for `now()`-derived defaults. */
  timeZone?: string;
}

/** DI token carrying the nearest {@link DoranDefaults}. */
export const DORAN_DEFAULTS = new InjectionToken<DoranDefaults>('DORAN_DEFAULTS');

/**
 * Provides Doran defaults to its content subtree via Angular DI. Request-scoped,
 * so it's SSR-safe (Angular Universal): the same `locale`/`timeZone` render on the
 * server and the client, avoiding digit hydration mismatches. Components resolve
 * `explicit input → provider`.
 */
@Component({
  selector: 'dr-provider',
  standalone: true,
  template: '<ng-content></ng-content>',
  providers: [{ provide: DORAN_DEFAULTS, useExisting: forwardRef(() => DoranProvider) }],
})
export class DoranProvider implements DoranDefaults {
  @Input() locale?: string;
  @Input() timeZone?: string;
}

// packages/react/src/provider.tsx
'use client';

import { getDefaultLocale, type Locale, type LocaleLike, resolveLocale } from '@doranjs/core';
import { createContext, type ReactNode, useContext, useMemo } from 'react';

/** Subtree defaults supplied by {@link DoranProvider}. */
export interface DoranDefaults {
  /** Formatting locale (Persian vs Latin digits, month names). */
  locale?: Locale;
  /** IANA time zone for `now()`-derived defaults (e.g. "today"). */
  timeZone?: string;
}

const DoranContext = createContext<DoranDefaults>({});

export interface DoranProviderProps {
  /** Locale for the subtree — a registered id (`'fa'`, `'en'`) or a `Locale`. */
  locale?: LocaleLike;
  /** IANA time zone (e.g. `'Asia/Tehran'`) for deterministic "today" under SSR. */
  timeZone?: string;
  children: ReactNode;
}

/**
 * Sets Doran defaults for its subtree. Unlike the mutable global
 * `setDefaultLocale()`, this is request-scoped, so it's safe for SSR: the same
 * `locale`/`timeZone` render on the server and the client, avoiding digit/tz
 * hydration mismatches. Components resolve their locale as
 * `prop → provider → global default`.
 */
export function DoranProvider({ locale, timeZone, children }: DoranProviderProps): ReactNode {
  const value = useMemo<DoranDefaults>(
    () => ({
      ...(locale ? { locale: resolveLocale(locale) } : {}),
      ...(timeZone ? { timeZone } : {}),
    }),
    [locale, timeZone],
  );
  return <DoranContext.Provider value={value}>{children}</DoranContext.Provider>;
}

/** Read the current {@link DoranDefaults} (empty object outside a provider). */
export function useDoranContext(): DoranDefaults {
  return useContext(DoranContext);
}

/** Resolve a component's locale: explicit prop → provider → global default. */
export function useResolvedLocale(locale?: Locale): Locale {
  const ctx = useContext(DoranContext);
  return locale ?? ctx.locale ?? getDefaultLocale();
}
