// examples/angular/src/demo/section.component.ts
import { Component, input } from '@angular/core';

// Groups all demos for one component under a titled, anchorable section.
@Component({
  selector: 'demo-section',
  standalone: true,
  template: `
    <section [id]="id()" class="section">
      <header class="section__head">
        <h2 class="section__title">{{ title() }}</h2>
        @if (intro()) {
          <p class="section__intro">{{ intro() }}</p>
        }
      </header>
      <div class="section__grid"><ng-content /></div>
    </section>
  `,
})
export class Section {
  readonly id = input.required<string>();
  readonly title = input.required<string>();
  readonly intro = input<string>();
}

// examples/svelte/src/demo/Section.svelte
<script lang="ts">
  // Groups all demos for one component under a titled, anchorable section.
  export let id: string;
  export let title: string;
  export let intro: string | undefined = undefined;
</script>

<section {id} class="section">
  <header class="section__head">
    <h2 class="section__title">{title}</h2>
    {#if intro}<p class="section__intro">{intro}</p>{/if}
  </header>
  <div class="section__grid">
    <slot />
  </div>
</section>
