// examples/react/src/demos/datepicker/Customization.tsx
import { DoranDate } from '@doranjs/core';
import { DoranDatePicker } from '@doranjs/react';
import { useState } from 'react';
import type { Locale } from '@doranjs/core';

export default function Customization({ locale }: { locale: Locale }) {
  const [value, setValue] = useState<DoranDate | null>(DoranDate.now());

  return (
    <DoranDatePicker
      value={value}
      onChange={setValue}
      locale={locale}
      footerActions={['today', 'clear']}
      iconPosition="right"
      textAlign="left"
      inputWidth="18rem"
      dropdownWidth="trigger"
    />
  );
}

// examples/angular/src/demos/datepicker/customization.component.ts
import { Component, input } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { DoranDate } from '@doranjs/core';
import { DoranDatePicker } from '@doranjs/angular';

@Component({
  selector: 'demo-dp-customization',
  standalone: true,
  imports: [ReactiveFormsModule, DoranDatePicker],
  template: `
    <dr-date-picker
      [formControl]="value"
      [locale]="lang()"
      [footerActions]="['today', 'clear']"
      iconPosition="right"
      textAlign="left"
      inputWidth="18rem"
      dropdownWidth="trigger"
    />
  `,
})
export class DpCustomization {
  readonly lang = input<'fa' | 'en'>('fa');
  readonly value = new FormControl<DoranDate | null>(DoranDate.now());
}
