// examples/angular/src/demos/rangepicker/default.component.ts
import { Component, input } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { DoranRangePicker, type DoranDateRange } from '@doranjs/angular';

// Click a start day, then an end day. The form value is a { start, end } of DoranDate.
@Component({
  selector: 'demo-rp-default',
  standalone: true,
  imports: [ReactiveFormsModule, DoranRangePicker],
  template: `<dr-range-picker [formControl]="value" [locale]="lang()" />`,
})
export class RpDefault {
  readonly lang = input<'fa' | 'en'>('fa');
  readonly value = new FormControl<DoranDateRange>({ start: null, end: null });
}

// examples/svelte/src/demos/rangepicker/Default.svelte
<script lang="ts">
  import { DoranRangePicker, type DoranDateRange } from '@doranjs/svelte';

  // Click a start day, then an end day. bind:value is a { start, end } of DoranDate.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDateRange = { start: null, end: null };
</script>

<DoranRangePicker bind:value locale={lang} />
