// examples/react/src/demos/rangepicker/MultiMonth.tsx
import { faIR, type Locale } from '@doranjs/core';
import { DoranRangePicker, type DateRange } from '@doranjs/react';
import { useState } from 'react';

// `numberOfMonths` renders several months side by side, easing the selection of
// longer ranges.
export default function MultiMonth({ locale = faIR }: { locale?: Locale }) {
  const [range, setRange] = useState<DateRange>({ start: null, end: null });
  return <DoranRangePicker value={range} onChange={setRange} numberOfMonths={2} locale={locale} />;
}

// examples/svelte/src/demos/rangepicker/MultiMonth.svelte
<script lang="ts">
  import { DoranRangePicker, type DoranDateRange } from '@doranjs/svelte';

  // months renders several months side by side, easing the selection of longer ranges.
  export let lang: 'fa' | 'en' = 'fa';
  let value: DoranDateRange = { start: null, end: null };
</script>

<DoranRangePicker bind:value locale={lang} months="2" />
