// examples/vue/src/demos/rangepicker/WithTrigger.vue
<script setup lang="ts">
import { DoranRangeDatePicker, type DoranDateRange } from '@doranjs/vue';
import { shallowRef } from 'vue';

// The web-component counterpart of React's DoranRangeDatePicker: one trigger holding
// two fields, either typable or fillable from the grid. The ends are kept in order.
const { lang = 'fa' } = defineProps<{ lang?: 'fa' | 'en' }>();
const range = shallowRef<DoranDateRange>({ start: null, end: null });
</script>

<template>
  <DoranRangeDatePicker v-model="range" :locale="lang" presets months="2" />
</template>

// examples/svelte/src/demos/rangepicker/WithTrigger.svelte
<script lang="ts">
  import { DoranRangeDatePicker } from '@doranjs/svelte';
  import type { DoranDateRange } from '@doranjs/svelte';

  // The web-component counterpart of React's DoranRangeDatePicker: one trigger
  // holding two fields, either typable or fillable from the grid.
  export let lang: 'fa' | 'en' = 'fa';

  let value: DoranDateRange = { start: null, end: null };
</script>

<DoranRangeDatePicker bind:value locale={lang} presets months="2" />
