// examples/vue/src/sections/DatePickerSection.vue
<script setup lang="ts">
import { useApp } from '../i18n/context';
import DemoCard from '../demo/DemoCard.vue';
import Section from '../demo/Section.vue';
import Default from '../demos/datepicker/Default.vue';
import DefaultSrc from '../demos/datepicker/Default.vue?raw';
import WithTime from '../demos/datepicker/WithTime.vue';
import WithTimeSrc from '../demos/datepicker/WithTime.vue?raw';
import Format from '../demos/datepicker/Format.vue';
import FormatSrc from '../demos/datepicker/Format.vue?raw';
import Customization from '../demos/datepicker/Customization.vue';
import CustomizationSrc from '../demos/datepicker/Customization.vue?raw';
import PickOnly from '../demos/datepicker/PickOnly.vue';
import PickOnlySrc from '../demos/datepicker/PickOnly.vue?raw';

const app = useApp();
</script>

<template>
  <Section id="datepicker" title="<DoranDatePicker>" :intro="app.t('dpIntro')">
    <DemoCard
      :title="app.t('dpDefaultTitle')"
      :description="app.t('dpDefaultDesc')"
      :code="DefaultSrc"
    >
      <Default :lang="app.lang()" />
    </DemoCard>
    <DemoCard :title="app.t('dpTimeTitle')" :description="app.t('dpTimeDesc')" :code="WithTimeSrc">
      <WithTime :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('dpFormatTitle')"
      :description="app.t('dpFormatDesc')"
      :code="FormatSrc"
    >
      <Format :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('dpPickOnlyTitle')"
      :description="app.t('dpPickOnlyDesc')"
      :code="PickOnlySrc"
    >
      <PickOnly :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('dpCustomizationTitle')"
      :description="app.t('dpCustomizationDesc')"
      :code="CustomizationSrc"
    >
      <Customization :lang="app.lang()" />
    </DemoCard>
  </Section>
</template>

// examples/svelte/src/sections/DatePickerSection.svelte
<script lang="ts">
  import { lang, t } from '../i18n/store';
  import DemoCard from '../demo/DemoCard.svelte';
  import Section from '../demo/Section.svelte';
  import Default from '../demos/datepicker/Default.svelte';
  import DefaultSrc from '../demos/datepicker/Default.svelte?raw';
  import WithTime from '../demos/datepicker/WithTime.svelte';
  import WithTimeSrc from '../demos/datepicker/WithTime.svelte?raw';
  import Format from '../demos/datepicker/Format.svelte';
  import FormatSrc from '../demos/datepicker/Format.svelte?raw';
  import Customization from '../demos/datepicker/Customization.svelte';
  import CustomizationSrc from '../demos/datepicker/Customization.svelte?raw';
  import PickOnly from '../demos/datepicker/PickOnly.svelte';
  import PickOnlySrc from '../demos/datepicker/PickOnly.svelte?raw';
</script>

<Section id="datepicker" title="<DoranDatePicker>" intro={$t('dpIntro')}>
  <DemoCard title={$t('dpDefaultTitle')} description={$t('dpDefaultDesc')} code={DefaultSrc}>
    <Default lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('dpTimeTitle')} description={$t('dpTimeDesc')} code={WithTimeSrc}>
    <WithTime lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('dpFormatTitle')} description={$t('dpFormatDesc')} code={FormatSrc}>
    <Format lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('dpPickOnlyTitle')} description={$t('dpPickOnlyDesc')} code={PickOnlySrc}>
    <PickOnly lang={$lang} />
  </DemoCard>
  <DemoCard
    title={$t('dpCustomizationTitle')}
    description={$t('dpCustomizationDesc')}
    code={CustomizationSrc}
  >
    <Customization lang={$lang} />
  </DemoCard>
</Section>
