// examples/vue/src/sections/RangePickerSection.vue
<script setup lang="ts">
import { useApp } from '../i18n/context';
import DemoCard from '../demo/DemoCard.vue';
import Section from '../demo/Section.vue';
import WithTrigger from '../demos/rangepicker/WithTrigger.vue';
import WithTriggerSrc from '../demos/rangepicker/WithTrigger.vue?raw';
import Default from '../demos/rangepicker/Default.vue';
import DefaultSrc from '../demos/rangepicker/Default.vue?raw';
import Presets from '../demos/rangepicker/Presets.vue';
import PresetsSrc from '../demos/rangepicker/Presets.vue?raw';
import MultiMonth from '../demos/rangepicker/MultiMonth.vue';
import MultiMonthSrc from '../demos/rangepicker/MultiMonth.vue?raw';
import Holidays from '../demos/rangepicker/Holidays.vue';
import HolidaysSrc from '../demos/rangepicker/Holidays.vue?raw';

const app = useApp();
</script>

<template>
  <Section id="rangepicker" title="<DoranRangePicker>" :intro="app.t('rpIntro')">
    <DemoCard
      :title="app.t('rpTriggerTitle')"
      :description="app.t('rpTriggerDesc')"
      :code="WithTriggerSrc"
    >
      <WithTrigger :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('rpDefaultTitle')"
      :description="app.t('rpDefaultDesc')"
      :code="DefaultSrc"
    >
      <Default :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('rpPresetsTitle')"
      :description="app.t('rpPresetsDesc')"
      :code="PresetsSrc"
      wide
    >
      <Presets :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('rpMultiTitle')"
      :description="app.t('rpMultiDesc')"
      :code="MultiMonthSrc"
      wide
    >
      <MultiMonth :lang="app.lang()" />
    </DemoCard>
    <DemoCard
      :title="app.t('rpHolidaysTitle')"
      :description="app.t('rpHolidaysDesc')"
      :code="HolidaysSrc"
    >
      <Holidays :lang="app.lang()" />
    </DemoCard>
  </Section>
</template>

// examples/svelte/src/sections/RangePickerSection.svelte
<script lang="ts">
  import { lang, t } from '../i18n/store';
  import DemoCard from '../demo/DemoCard.svelte';
  import Section from '../demo/Section.svelte';
  import Default from '../demos/rangepicker/Default.svelte';
  import DefaultSrc from '../demos/rangepicker/Default.svelte?raw';
  import Presets from '../demos/rangepicker/Presets.svelte';
  import PresetsSrc from '../demos/rangepicker/Presets.svelte?raw';
  import MultiMonth from '../demos/rangepicker/MultiMonth.svelte';
  import MultiMonthSrc from '../demos/rangepicker/MultiMonth.svelte?raw';
  import Holidays from '../demos/rangepicker/Holidays.svelte';
  import HolidaysSrc from '../demos/rangepicker/Holidays.svelte?raw';
</script>

<Section id="rangepicker" title="<DoranRangePicker>" intro={$t('rpIntro')}>
  <DemoCard title={$t('rpTriggerTitle')} description={$t('rpTriggerDesc')} code={WithTriggerSrc}>
    <WithTrigger lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('rpDefaultTitle')} description={$t('rpDefaultDesc')} code={DefaultSrc}>
    <Default lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('rpPresetsTitle')} description={$t('rpPresetsDesc')} code={PresetsSrc} wide>
    <Presets lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('rpMultiTitle')} description={$t('rpMultiDesc')} code={MultiMonthSrc} wide>
    <MultiMonth lang={$lang} />
  </DemoCard>
  <DemoCard title={$t('rpHolidaysTitle')} description={$t('rpHolidaysDesc')} code={HolidaysSrc}>
    <Holidays lang={$lang} />
  </DemoCard>
</Section>
