// examples/svelte/src/demos/agenda/Days.svelte
<script lang="ts">
  import { DoranDate } from '@doranjs/core';
  import { DoranAgenda } from '@doranjs/svelte';
  import type { AgendaEvent } from '@doranjs/wc';

  // `days` sets how many days to render — here a 3-day view starting today.
  export let lang: 'fa' | 'en' = 'fa';
  const start = DoranDate.now().startOf('day');
  const events: AgendaEvent[] = [
    { id: '1', date: start, title: 'امروز: تماس با مشتری', color: 'var(--doran-primary)' },
    { id: '2', date: start.addDays(2), title: 'پس‌فردا: انتشار گزارش' },
  ];
</script>

<DoranAgenda {start} days={3} {events} locale={lang} />

// examples/vue/src/demos/agenda/Days.vue
<script setup lang="ts">
import { DoranDate } from '@doranjs/core';
import { DoranAgenda } from '@doranjs/vue';
import type { AgendaEvent } from '@doranjs/wc';

// `days` sets how many days to render — here a 3-day view starting today.
defineProps<{ lang?: 'fa' | 'en' }>();
const start = DoranDate.now().startOf('day');
const events: AgendaEvent[] = [
  { id: '1', date: start, title: 'امروز: تماس با مشتری', color: 'var(--doran-primary)' },
  { id: '2', date: start.addDays(2), title: 'پس‌فردا: انتشار گزارش' },
];
</script>

<template>
  <DoranAgenda :start="start" :days="3" :events="events" :locale="lang ?? 'fa'" />
</template>
